import { Hero } from '@/components/Hero'
import { MainLayout } from '@/layouts/MainLayout'
import Head from 'next/head'
import { Fragment, useState } from 'react'

export default function Home() {
	return (
		<>
			<Head>
				<title></title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MainLayout>
				<Hero />
			</MainLayout>
		</>
	)
}
